export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_START = "LOGIN_START";
export const SIGNUP_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_FAILED = "LOGIN_FAILED";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const LOGOUT_USER = "LOGOUT_USER";

export const NEW_ANNOUNCEMENT_ADDED = "NEW_ANNOUNCEMENT_ADDED";
export const ADD_CONVERSATION_NAME = "ADD_CONVERSATION_NAME";
export const SELECTED_SEARCHED_MESSAGE = "SELECTED_SEARCHED_MESSAGE";
export const ADD_CONVERSATION_NAMES = "ADD_CONVERSATION_NAMES";

export const SHOW_LOGOUT_FROM_OTHER_DEVICES = "TOGGLE_LOGOUT_FROM_OTHER_DEVICES"
export const CLOSE_LOGOUT_FROM_OTHER_DEVICES = "CLOSE_LOGOUT_FROM_OTHER_DEVICES"